### ISSUE TITLE
RSS 支持

### ISSUE THREAD

**Issue by daleyshek** [gocn/news#80]
什么时候支持 RSS订阅

**Comment by ipfans** [comment]
@daleyshek 试一下社区的订阅？ https://gocn.vip/topics/feed

**Comment by Eminlin** [comment]
目前这个没办法请求了

**Comment by ipfans** [comment]
@Eminlin 现在社区是换了自己写的程序，RSS功能应该没作。可以提个需求给开发

**Comment by Eminlin** [comment]
> @Eminlin 现在社区是换了自己写的程序，RSS功能应该没作。可以提个需求给开发

@ipfans 原来如此 本来是读取 github commit 记录 https://github.com/gocn/news/commits.atom 发现不是很满意

**Comment by bensinos** [comment]
什么时候添加RSS啊
